
import javax.swing.JOptionPane;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author ILHAM
 */
public class frame1 extends javax.swing.JFrame {
    String temp = "";
    Double ti,bt,h1;
    /**
     * Creates new form frame1
     */
    public frame1() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        saran = new javax.swing.JTextField();
        Nama = new javax.swing.JTextField();
        Tinggi = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        pere = new javax.swing.JRadioButton();
        laki = new javax.swing.JRadioButton();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        ideal = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        Berat = new javax.swing.JTextField();
        hasil = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        jLabel1.setText("CEK IDEAL TUBUH");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(180, 20, 100, 40);

        jLabel3.setText("Nama");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(100, 80, 50, 14);

        jLabel4.setText("Tinggi");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(100, 130, 50, 14);

        saran.setEditable(false);
        getContentPane().add(saran);
        saran.setBounds(30, 460, 390, 30);
        getContentPane().add(Nama);
        Nama.setBounds(190, 70, 150, 30);
        getContentPane().add(Tinggi);
        Tinggi.setBounds(190, 120, 60, 30);

        jLabel5.setText("Jenis Kelamin");
        getContentPane().add(jLabel5);
        jLabel5.setBounds(100, 220, 70, 14);

        jLabel6.setText("Kg");
        getContentPane().add(jLabel6);
        jLabel6.setBounds(260, 170, 30, 30);

        jLabel7.setText("Berat Badan");
        getContentPane().add(jLabel7);
        jLabel7.setBounds(100, 180, 70, 14);

        buttonGroup1.add(pere);
        pere.setText("Perempuan");
        pere.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pereActionPerformed(evt);
            }
        });
        getContentPane().add(pere);
        pere.setBounds(300, 220, 93, 23);

        buttonGroup1.add(laki);
        laki.setText("Laki - Laki");
        laki.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                lakiActionPerformed(evt);
            }
        });
        getContentPane().add(laki);
        laki.setBounds(190, 220, 90, 23);

        jButton1.setText("Keluar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1);
        jButton1.setBounds(300, 270, 90, 30);

        jButton2.setText("Hitung");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2);
        jButton2.setBounds(90, 270, 70, 30);

        jButton3.setText("Coba Lagi");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton3);
        jButton3.setBounds(190, 270, 90, 30);

        jLabel8.setText("Kg");
        getContentPane().add(jLabel8);
        jLabel8.setBounds(260, 120, 30, 30);

        jLabel9.setText("Hasil Diagnosa Kesehatan");
        getContentPane().add(jLabel9);
        jLabel9.setBounds(160, 380, 160, 30);
        getContentPane().add(ideal);
        ideal.setBounds(270, 330, 60, 30);

        jLabel10.setText("Kg");
        getContentPane().add(jLabel10);
        jLabel10.setBounds(340, 330, 30, 30);

        jLabel11.setText("Berat Badan Ideal Anda Adalah");
        getContentPane().add(jLabel11);
        jLabel11.setBounds(90, 330, 170, 30);
        getContentPane().add(Berat);
        Berat.setBounds(190, 170, 60, 30);

        hasil.setEditable(false);
        getContentPane().add(hasil);
        hasil.setBounds(30, 410, 390, 30);

        setBounds(0, 0, 468, 565);
    }// </editor-fold>//GEN-END:initComponents

    private void pereActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pereActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_pereActionPerformed

    private void lakiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_lakiActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_lakiActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        if(Nama.getText().equals("")|| Tinggi.getText().equals("")
                |(Berat.getText().equals(""))) 
                {JOptionPane.showMessageDialog(null, "data harus diisikan semua");}
        else if (laki.isSelected() || pere.isSelected())
        {
            try
            {
                Proses();
            }
            catch(Exception e)
            {
                JOptionPane.showMessageDialog(null,"Inputan Ada yang belum diisi");
            }
        }
        else
        {
            JOptionPane.showMessageDialog(null,"Apa Jenis Kelamin Anda ?");
        }
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        Nama.setText("");
        Berat.setText("");
        Tinggi.setText("");
        ideal.setText("");
        hasil.setText("");
        saran.setText("");
        buttonGroup1.clearSelection();
                // TODO add your handling code here:
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
    System.exit(0);        // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frame1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frame1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frame1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frame1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new frame1().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField Berat;
    private javax.swing.JTextField Nama;
    private javax.swing.JTextField Tinggi;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JTextField hasil;
    private javax.swing.JTextField ideal;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JRadioButton laki;
    private javax.swing.JRadioButton pere;
    private javax.swing.JTextField saran;
    // End of variables declaration//GEN-END:variables

    private void Proses() {
        ti = Double.parseDouble(Tinggi.getText());
        bt = Double.parseDouble(Berat.getText());
        
        if(laki.isSelected())
        {
            h1 = (ti - 100) * 1;
        }
        else if(pere.isSelected())    
        {
            h1 = (ti - 104) * 1;
        }
        temp = Double.toString(h1.intValue());
        
        if(h1 < bt)
        {
            ideal.setText(temp);
            hasil.setText("Maaf " + Nama.getText() + " , Sepertinya Anda Gendatz");
            saran.setText("Banyaklah Berolahraga dan hindari makanan yang berkolesterol");
        }
        else if(h1 > bt)
        {
            ideal.setText(temp);
            hasil.setText("Maaf " + Nama.getText() + " , Sepertinya Anda Kuruz");
            saran.setText("Banyaklah mengonsumsi makanan yang berkabohidrat");
        }
        else
        {
            ideal.setText(temp);
            hasil.setText(Nama.getText() + " , Sepertinya Anda Sudah Ideal");
            saran.setText("Lanjutkan pola makan teratur dan gaya hidup sehat");
        }
//To change body of generated methods, choose Tools | Templates.
    }
}
